---
- name: common - install packages
  remote_user: root
  apt: pkg={{ item }} update_cache=yes state=latest cache_valid_time=4320
  with_items:
    - g++
    - make
    - curl
    - libssl-dev
    - python-dev
    - git-core
    - mercurial
    - sqlite3
    - libsqlite3-dev
    - vim
